const fs = require('fs');
const path = require('path');

const docsDir = './src';

export default {
  default: fs.readdirSync(docsDir)
    .filter(name => fs.statSync(path.join(docsDir, name)).isDirectory())
    .filter(name => name !== "pages")
    .map(dirName => ({
      type: "category",
      label: dirName[0].toUpperCase() + dirName.slice(1).replaceAll("-"," "),
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName
        },
      ],
    }))
}